// LOGIN
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

// WALLET
export const WALLET_EDIT = 'WALLET_EDIT';
export const WALLET_DELETE = 'WALLET_DELETE';
export const WALLET_CREATE = 'WALLET_CREATE';
export const WALLET_FETCH_ALL = 'WALLET_FETCH_ALL';
export const WALLET_FETCH_SINGLE = 'WALLET_FETCH_SINGLE';

// EXPENSES
export const EXPENSES_EDIT = 'EXPENSES_EDIT';
export const EXPENSES_DELETE = 'EXPENSES_DELETE';
export const EXPENSES_CREATE = 'EXPENSES_CREATE';
export const EXPENSES_FETCH_ALL = 'EXPENSES_FETCH_ALL';
export const EXPENSES_FETCH_SINGLE = 'EXPENSES_FETCH_SINGLE';